import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

# decorations = "Transparent"

opacity = 0.8
blur = true

option_as_alt = "both"

[font]
normal.family = "JetBrainsMono Nerd Font"

#regular
size = 15
